language: php
php:
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'CREATE DATABASE IF NOT EXISTS BOOKXCHANGE;'
  - mysql BOOKXCHANGE < database/book.sql
  - npm install karma phantomjs-prebuilt jasmine-core karma-phantomjs-launcher karma-jasmine --save-dev
  
script:
  - ./vendor/bin/phpunit
  - karma start --single-run --browsers PhantomJS karma.conf.js

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

notifications:
  email: false
