language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
services:
  - mysql
  
install:
  - pecl install pdo
  - pecl install pdo_mysql
  
before_script:
  - mysql -u root -e 'CREATE DATABASE BOOKXCHANGE;'
  - mysql -u root BOOKXCHANGE < database/book.sql
  
after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
